services:
  frontend:
    build: 
      context: ./client/.
      args: 
        PUBLIC_BACKEND_URL: '${BACKEND_URL}'
    restart: unless-stopped
    ports:
      - "4321:4321"
    container_name: hyperslice-frontend
  api:
    ports:
      - "3001:3001"
    build: ./api/.
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - hyperslice
    env_file:
      - .env
    container_name: hyperslice-api
  db:
    image: postgres:latest
    restart: unless-stopped
    shm_size: 256mb
    ports:
      - "5432:5432"
    volumes:
      - hyperslice-db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER='${POSTGRES_USER}'
      - POSTGRES_PASSWORD='${POSTGRES_PASSWORD}'
      - POSTGRES_DB='${POSTGRES_DATABASE}'
    container_name: hyperslice-db
    networks:
      - hyperslice
volumes:
  hyperslice-db:
    driver: local
networks:
  hyperslice:
    driver: bridge